language: node_js
node_js:
  - 6
  - 8
  - node

matrix:
  allow_failures:
  - node_js: node

before_install:
  - cd lambda

script:
  - npm test

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: 8
      before_install: (cd lambda && npm install)
      script: make compile
      before_deploy: make copy
      deploy:
        provider: lambda
        function_name: pammie
        region: eu-west-1
        role: arn:aws:iam::665717792942:role/service-role/parliament
        runtime: nodejs8.10
        handler_name: handler
        access_key_id: AKIAINPNNSVAFWAW5KUQ
        environment_variables:
          - NODE_ENV=production
        publish: true
        timeout: 60
        zip: lambda/dist
